export const Nuances = {
    "EXG": "Extrême Gauche",
    "DIV": "Divers",
    "MNA": "Mouvement National",
    "VEC": "EELV - Europe Écologie Les Verts",
    "GAU": "Gauche - Parti Socialiste",
    "COM": "Communiste",
    "UDF": "Union pour la Démocratie Française",
    "CPNT": "Chasse, Pêche, Nature, Tradition",
    "FRN": "Front National",
    "REG": "Régionaliste",
    "DTE": "Droite",
    "ECO": "Écologiste",
    "DVD": "Divers Droite",
    "MNR": "Mouvement National Républicain",
    "FN": "Front National",
    "DVG": "Divers Gauche",
    "DL": "Démocratie Libérale",
    "SOC": "Parti Socialiste",
    "RPR": "Rassemblement pour la République",
    "MDC": "Mouvement des Citoyens",
    "PRG": "Parti Radical de Gauche",
    "RPF": "Rassemblement du Peuple Français",
    "UMP": "Union pour un Mouvement Populaire",
    "PREP": "NON CONNU",
    "MPF": "Mouvement pour la France",
    "LO": "Lutte Ouvrière",
    "LCR": "Ligue Communiste Révolutionnaire",
    "EXD": "Extrême Droite",
    "RDG": "Radicaux de Gauche",
    "CEN": "Le Centre pour la France",
    "FG": "Front de Gauche - PCF - Parti de Gauche - Ensemble",
    "UDFD" : "UDF - Mouvement démocrate",
    "ALLI" : "Alliance centriste",
    "PRV" : "Parti radical valoisien",
    "NCE" : "Nouveau Centre",
    "LFN": "Liste Front National",
    "LXG": "Liste Extrême Gauche",
    "LGA": "Liste de Gauche",
    "LVE": "Liste des Verts",
    "LDR": "Liste Droite",
    "LXD": "Liste Extrême Droite",
    "LDV": "Liste Divers",
    "LEC": "Liste Ecologiste",
    "LDD": "Liste Divers Droite",
    "LCP": "Listes Chasse,pêche,nature et traditions",
    "LDG": "Listes divers gauche",
    "LRG": "Listes régionaliste",
    "AUT": "Autre",
    "LAUT": "Liste Autre",
    "LPS": "Liste Parti Socialiste",
    "LPC": "Liste Communiste",
    "LUMP": "Liste Union pour un Mouvement Populaire",
    "LUDF": "Liste Union pour la Démocratie Française",
    "LDVD": "Liste Divers Droite",
    "LDVG": "Liste Divers Gauche",
    "LEXG": "Liste Extrême Gauche",
    "LVEC": "Liste EELV - Europe Écologie Les Verts",
    "LSOC": "Liste Parti Socialiste",
    "LCOP": "Liste Front de Gauche - PCF - Parti de Gauche - Ensemble",
    "LCMD": "Liste Centriste Modem",
    "LMAJ": "Liste Majorité Présidentielle",
    "LEXD": "Liste Extrême Droite",
    "LREG": "Liste Régionaliste",
    "LUG": "Liste Union de la Gauche",
    "PG": "Parti de Gauche",
    "MNC": "Majorité Présidentielle",
    "MODM": "Modem",
    "MAJ": "Majorité",
    "LDIV": "Liste Divers",
    "LFG": "Liste Front de Gauche - PCF - Parti de Gauche - Ensemble",
    "LUC": "Liste Union du Centre",
    "LCOM": "Liste Communiste",
    "LVEG": "Liste Verts Écologistes",
    "LDLF": "Liste Debout la France",
    "LUD": "Liste Union de la Droite",
    "LECO": "Liste Écologiste",
    "LLR": "Liste Les Républicains",
    "LRDG": "Liste Radicaux de Gauche",
    "LMDM": "Liste Modem",
    "LUDI": "Liste UDI",
    "BC-UG": "Binôme d'Union à Gauche",
    "BC-FN": "Binôme Front National",
    "BC-UD": "Binôme Union de la Droite",
    "BC-VEC": "Binôme EELV - Europe Écologie Les Verts",
    "BC-COM": "Binôme Communiste",
    "BC-DVD": "Binôme Divers Droite",
    "BC-DIV": "Binôme Divers",
    "BC-UMP": "Binôme UMP",
    "BC-DVG": "Binôme Divers Gauche",
    "BC-SOC": "Binôme Parti Socialiste",
    "BC-UDI": "Binôme UDI",
    "BC-FG": "Binôme Front de Gauche",
    "BC-EXG": "Binôme Extrême Gauche",
    "BC-RDG": "Binôme Radicaux de Gauche",
    "BC-DLF": "Binôme Debout la France",
    "BC-EXD": "Binôme Extrême Droite",
    "BC-MDM": "Binôme Modem",
    "BC-PG": "Binôme Parti de Gauche",
    "BC-UC": "Binôme Union du Centre",
    "FI": "France Insoumise",
    "REM": "La République En Marche",
    "UDI": "Union des Démocrates et Indépendants",
    "LR": "Les Républicains",
    "DLF": "Debout la France",
    "MDM": "Modem",
    "BC-UCD": "Binôme d'Union au centre et à droite	",
    "BC-RN": "Binôme Rassemblement National",
    "BC-UXD": "Binôme Union Extrême Droite",
    "BC-UGE": "Binôme Union de la Gauche et des Écologistes",
    "BC-DSV": "Binôme Divers souverainiste",
    "BC-LR": "Binôme Les Républicains",
    "BC-DVC": "Binôme Divers Centre",
    "BC-UCG": "Binôme Union du Centre et Gauche",
    "BC-REM": "Binôme La République En Marche",
    "BC-FI": "Binôme France Insoumise",
    "BC-ECO": "Binôme Écologiste",
    "BC-REG": "Binôme Régionaliste",
    "BC-GJ": "Binôme Gilets jaunes",
    "LGJ": "Liste Gilets jaunes",
    "LRN": "Liste Rassemblement National",
    "LDSV": "Liste Divers souverainistes",
    "LUGE": "Liste Union de la Gauche et des Écologistes",
    "LDVE": "Liste Divers Écologiste",
    "LDVC": "Liste Divers Centre",
    "LUCD": "Liste d'Union au centre et à droite",
    "LGEN": "Liste Génération•s",
    "LFI": "Liste La France Insoumise",
    "LREM": "Liste La République En Marche",
    "DXG": "Divers Extrême Gauche",
    "NUP": "Nouvelle Union Populaire Écologique et Sociale",
    "ENS": "Ensemble",
    "DVC": "Divers Centre",
    "DSV": "Divers souverainistes",
    "REC": "Reconquête",
    "RN": "Rassemblement National",
    "DXD": "Divers Extrême Droite"  
  }



  export const GroupedNuances = {
    "Extrême Gauche": ["EXG", "LO", "LCR", "LXG", "LEXG", "BC-EXG", "DXG"],
    "La France Insoumise": ["FG", "LCOP", "PG", "LFG", "BC-FG", "BC-PG", "FI", "BC-FI", "LFI"],
    "Parti Communiste": ["COM", "LPC", "LCOM", "BC-COM"],
    "Generation•s": ["LGEN", "BC-GEN"],
    "EELV": ["VEC", "LVE", "LVEC", "LVEG", "BC-VEC"],
    "Ecologistes": ["ECO", "LEC", "LECO", "BC-ECO", "LDVE"],
    "Divers Gauche": ["DVG", "MDC", "LDG", "LDVG", "BC-DVG"],
    "Parti Socialiste": ["GAU", "SOC", "LGA", "LPS", "LSOC", "BC-SOC"],
    "Parti Radical de Gauche": ["PRG", "RDG", "BC-RDG"],
    "Union à gauche": ["LUG", "BC-UG", "BC-UGE", "BC-UCG", "LUGE", "NUP"],
    "Centriste": ["UDF", "DL", "CEN", "UDFD", "ALLI","PRV", "NCE", "LUDF", "LUC", "BC-UC", "BC-DVC", "LDVC","DVC"],
    "Ensemble !": ["LCMD", "MNC", "MODM", "MDM", "LMDM", "BC-MDM", "REM", "BC-REM", "LREM", "ENS"],
    "Les Républicains": ["DTE", "RPR", "UMP", "BC-UMP", "LDR"," MAJ", "LMAJ", "LUMP", "LDVD", "LLR", "LR", "BC-LR"],
    "Union à droite": ["LUD", "BC-UD", "BC-UCD", "LUCD"],
    "Divers Droite": ["DVD", "LDD", "LUDI", "BC-DVD", "BC-UDI", "UDI"],
    "Rassemblement National": ["FRN", "FN", "LFN", "BC-FN", "BC-RN", "RN", "LRN"],
    "Extrême Droite": ["MNA", "MNR", "MPF", "RPF", "EXD", "LXD", "LEXD", "LDLF", "BC-DLF", "BC-EXD", "DLF", "BC-UXD", "DSV", "LDSV", "REC", "DXD"],
    "Régionaliste": ["REG", "LRG", "LREG", "BC-REG"],
    "Divers autres": ["DIV", "CPNT", "PREP", "LDV", "LCP", "AUT", "LAUT", "LDIV", "BC-DIV", "BC-GJ", "LGJ"],
  };


  export const GroupedGroupsNuances = {
    "Extrême Gauche" : ["Extrême Gauche"],
    "Gauche" : ["La France Insoumise", "Parti Communiste", "Generation•s", "EELV", "Ecologistes", "Divers Gauche", "Parti Socialiste", "Parti Radical de Gauche", "Union à gauche"],
    "Centre" : ["Centriste", "Ensemble !"],
    "Droite" : ["Les Républicains", "Union à droite", "Divers Droite"],
    "Extrême Droite" : ["Rassemblement National", "Extrême Droite"],
    "Autres" : ["Régionaliste", "Divers autres"]
  };

  export const colorNuances = {
    "Extrême Gauche": "rgb(206, 0, 0)",                // Darker Red
    "La France Insoumise": "rgb(179, 0, 179)",          // Red-Purple
    "Parti Communiste": "rgb(255, 0, 0)",              // Bright Red
    "Generation•s": "rgb(140, 0, 70)",                 // Dark Rose
    "EELV": "rgb(0, 135, 0)",                          // Dark Green
    "Ecologistes": "rgb(0, 200, 0)",                   // Green
    "Divers Gauche": "rgb(255, 100, 100)",             // Lighter Red
    "Parti Socialiste": "rgb(255, 40, 120)",           // Magenta
    "Parti Radical de Gauche": "rgb(130, 0, 130)",     // Dark Purple
    "Union à gauche": "rgb(206, 0, 0)",                // Darker Red
    "Centriste": "rgb(0, 180, 180)",                   // Turquoise
    "Ensemble !": "rgb(120, 170, 220)",                // Lighter Blue
    "Les Républicains": "rgb(0, 0, 255)",              // Blue
    "Union à droite": "rgb(0, 0, 130)",                // Dark Blue
    "Divers Droite": "rgb(0, 90, 180)",                // Darker Blue
    "Rassemblement National": "rgb(40, 40, 40)",       // Dark Gray
    "Extrême Droite": "rgb(156, 70, 38)",              // Dark Brown
    "Régionaliste": "rgb(255, 130, 0)",                // Orange
    "Divers autres": "rgb(255, 200, 0)",               // Gold
  };  
  

export const list_elections = {
        'ER99_Bvot' : "Européennes 1999",
        'CN01_BVot_T1T2' : "Cantonales 2001",
        'LG02_BVot_T1T2' : "Législatives 2002",
        'CN04_BVot_T1T2' : "Cantonales 2004",
        'RG04_BVot_T1T2' : "Régionales 2004",
        'ER04_BVot' : "Européennes 2004",
        'LG07_Bvot_T1T2' : "Législatives 2007",
        'CN08_BVot_T1T2': "Cantonales 2008",
        'ER09_BVOT' : "Européennes 2009",
        'RG10_BVot_T1T2' : "Régionales 2010",
        'CN11_BVot_T1T2' : "Cantonales 2011",
        'LG12_Bvot_T1T2' : "Législatives 2012",
        'ER14_BVOT' : "Européennes 2014",
        'RG15_BVot_T1T2' : "Régionales 2015",
        'DP15_Bvot_T1T2' : "Départementales 2015",
        'LG17_BVot_T1T2' : "Législatives 2017",
        'ER19_BVot' : "Européennes 2019",
        'DP21_BVot_T1T2' : "Départementales 2021",
        'RG21_BVot_T1T2' : "Régionales 2021",
        'LG22_BVot_T1T2' : "Législatives 2022",    
}

export const elections = [
    'ER99_Bvot',
    'CN01_BVot_T1T2',
    'LG02_BVot_T1T2',
    'CN04_BVot_T1T2',
    'RG04_BVot_T1T2',
    'ER04_BVot',
    'LG07_Bvot_T1T2',
    'CN08_BVot_T1T2',
    'ER09_BVOT',
    'RG10_BVot_T1T2',
    'CN11_BVot_T1T2',
    'LG12_Bvot_T1T2',
    'ER14_BVOT',
    'RG15_BVot_T1T2',
    'DP15_Bvot_T1T2',
    'LG17_BVot_T1T2',
    'ER19_BVot',
    'DP21_BVot_T1T2',
    'RG21_BVot_T1T2',
    'LG22_BVot_T1T2',
  ];
  
const europ19 = {
'LA FRANCE INSOUMISE' : "LFI",
'UNE FRANCE ROYALE' : "LEXD",
'LA LIGNE CLAIRE' : "LEXD",
'PARTI PIRATE' : "LDIV",
'RENAISSANCE' : "LREM",
'Dï¿½MOCRATIE REPRï¿½SENTATIVE' : "LDIV",
'ENSEMBLE PATRIOTES' : "LEXD",
'PACE' : "LDIV",
'URGENCE ï¿½COLOGIE' : "LDVE",
'LISTE DE LA RECONQUï¿½TE' : "LEXD",
'LES EUROPï¿½ENS' : "LDIV",
'ENVIE DEUROPE' : "LSOC",
'PARTI FED. EUROPï¿½EN' : "LDIV",
'INITIATIVE CITOYENNE : ' : "LDIV",
'DEBOUT LA FRANCE' : "LDLF",
'ALLONS ENFANTS' : "LDIV",
'Dï¿½CROISSANCE 2019' : "LDIV",
'LUTTE OUVRIï¿½RE' : "LEXG",
'POUR LEUROPE DES GENS' : "LCOM",
'ENSEMBLE POUR LE FREXIT' : "LEXD",
'LISTE CITOYENNE' : "LGEN",
'ï¿½ VOIX ï¿½GALES' : "LDIV",
'PRENEZ LE POUVOIR' : "LRN", 
'NEUTRE ET ACTIF' : "LDIV",
'Rï¿½VOLUTIONNAIRE' : "LEXG",
'ESPERANTO' : "LDIV",
'ï¿½VOLUTION CITOYENNE' : "LDIV",
'ALLIANCE JAUNE' : "LGJ", 
'UNION DROITE-CENTRE' : "LUCD",
'EUROPE ï¿½COLOGIE' : "LECO", 
'PARTI ANIMALISTE' : "LDVE",
'LES OUBLIES DE LEUROPE' : "LDIV",
'UDLEF' : "LDIV",
'EUROPE AU SERVICE PEUPLES' : "LDIV",

}






